version: 0.10.0.{build}
image: Visual Studio 2017

before_build:
- cmd: >-
    git clone https://bitbucket.org/wowmodelviewer/wmv_sdk
    
    cd wmv_sdk

    git reset --hard 5b71968 

    .\wmv_set_env.bat

    mkdir C:\projects\wowmodelviewer\build

    cd C:\projects\wowmodelviewer\build

    cmake -G "Visual Studio 15 2017" -DBUILDNUMBER=%APPVEYOR_BUILD_NUMBER% ..\src

build_script:
- cmd: >-
    cmake --build . --target release --config Release
    
    cd C:\projects\wowmodelviewer\bin

    ren WMV_Installer.exe WMV_Installer_v%APPVEYOR_BUILD_VERSION%.exe

test: off

artifacts:
- path: bin\WMV_Installer_v%APPVEYOR_BUILD_VERSION%.exe

for:
-
  branches:
    only:
      - develop

  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
